-- Step 1: comment 컬럼 추가
ALTER TABLE quote_templates ADD COLUMN IF NOT EXISTS comment TEXT DEFAULT '';

-- Step 2: 항목별 comment 데이터 업데이트
UPDATE quote_templates SET comment = '아파트 내규에 따라 변동가능' WHERE item_name = '공사신고/입주민 동의서';
UPDATE quote_templates SET comment = '구조변경시 진행필요' WHERE item_name = '행위허가 대행료';
UPDATE quote_templates SET comment = '아파트 내규에 따라 변동가능' WHERE item_name = '승강기 사용료';
UPDATE quote_templates SET comment = '아파트 내규에 따라 변동가능' WHERE item_name = '승강기 보양료';
UPDATE quote_templates SET comment = '아파트 내규에 따라 변동가능' WHERE item_name = '동선 보양료';
UPDATE quote_templates SET comment = '플로베니아, 종이보양지, 종이각대 등' WHERE item_name = '공정중 현장 보양 및 시공';
UPDATE quote_templates SET comment = '작업등작업' WHERE item_name = '가설전기';
UPDATE quote_templates SET comment = '아파트 내규에 따라 변동가능' WHERE item_name = '주차요금';
UPDATE quote_templates SET comment = '1톤 1차 폐기물 처리 비용' WHERE item_name = '공정 중 폐기물처리';
UPDATE quote_templates SET comment = '구조변경시 추가가능' WHERE item_name = '스프링쿨러 이설';
UPDATE quote_templates SET comment = '교체 모델에 따라 변동가능' WHERE item_name = '인터폰 교체';
UPDATE quote_templates SET comment = '교체 모델에 따라 변동가능' WHERE item_name = '보일러컨트롤러 교체';
UPDATE quote_templates SET comment = '교체 모델에 따라 변동가능' WHERE item_name = '도어락 교체';
UPDATE quote_templates SET comment = '누수여부에 따라 진행가능' WHERE item_name = '샤시 외부 코킹작업';
UPDATE quote_templates SET comment = '노후 여부에 따라 추가가능' WHERE item_name = '샤시 손잡이 교체';
UPDATE quote_templates SET comment = '노후 여부에 따라 추가가능' WHERE item_name = '방충망 교체';
UPDATE quote_templates SET comment = '*고객님 섭외*' WHERE item_name = '입주청소';
UPDATE quote_templates SET comment = '사다리차, 또는 스카이 필요 한 경우' WHERE item_name = '장비대';
UPDATE quote_templates SET comment = '바닥 마루 종류에 따라 추가가능( ex : 철거가 어려운 합판 마루)' WHERE item_name = '인건비 / 폐기물 처리비용';
UPDATE quote_templates SET comment = '1차 액상방수\n2차, 3차 아쿠아디펜스 방수 작업' WHERE item_name = '욕실 방수설비';
UPDATE quote_templates SET comment = '전체 소방감지기 교체\n(감지기 종류에 따라 비용변동가능)' WHERE item_name = '소방설비';
UPDATE quote_templates SET comment = '길이에 따라 책정' WHERE item_name = '수도/배관 이설 작업';
UPDATE quote_templates SET comment = '5개까지 추가비용 없음.' WHERE item_name = '콘센트 신설(까대기 작업)';
UPDATE quote_templates SET comment = '스피커, 누전차단기, 감지기, 분전함 교체' WHERE item_name = '분전함 교체';
UPDATE quote_templates SET comment = '이건창호 기준\n실제 현장 실측 후 비용 변동 있고, 현재 견적은 대략적인 예상 비용입니다.' WHERE item_name = '창호교체비용';
UPDATE quote_templates SET comment = '설계에 따라 목공사 비용은 변동될 수 있습니다.' WHERE item_name = '가벽생성';
UPDATE quote_templates SET comment = '6명 * 10일 작업기준' WHERE item_name = '인건비';
UPDATE quote_templates SET comment = 'ABS도어 + 경첩 + 손잡이 포함' WHERE item_name = '일반 여닫이 문';
UPDATE quote_templates SET comment = 'ABS도어 + 슬라이딩레일 + 손잡이 포함' WHERE item_name = '슬라이딩 문';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '현관바닥타일';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '주방 벽타일';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '거실욕실 타일';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '거실욕실 타일(자녀방)';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '안방욕실 타일';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '베란다 타일';
UPDATE quote_templates SET comment = '지정타일 기준(로스포함)' WHERE item_name = '거실,주방 바닥타일';
UPDATE quote_templates SET comment = '모자이크 타일 시공시 필요한 경우' WHERE item_name = '막타일';
UPDATE quote_templates SET comment = '제작' WHERE item_name = '트렌치 유가';
UPDATE quote_templates SET comment = '타일마감 고급유가' WHERE item_name = '타일유가';
UPDATE quote_templates SET comment = '세탁배수유가, 일반형' WHERE item_name = '일반 배수유가';
UPDATE quote_templates SET comment = '드라이픽스,압착,코너비드 외' WHERE item_name = '부자재';
UPDATE quote_templates SET comment = '타일시공' WHERE item_name = '시공비( 600*600)';
UPDATE quote_templates SET comment = '타일시공' WHERE item_name = '시공비(모자이크타일)';
UPDATE quote_templates SET comment = '타일시공' WHERE item_name = '시공비(600*600 이상, 박판타일)';
UPDATE quote_templates SET comment = '화물파레트' WHERE item_name = '운임';
UPDATE quote_templates SET comment = '타일양중' WHERE item_name = '양중';
UPDATE quote_templates SET comment = '옵션 선택사항( 인건비가 많이 드는 고가의 줄눈시공으로 유지관리, 오염에 강합니다.)' WHERE item_name = '케라폭시 시공';
UPDATE quote_templates SET comment = '벤자민 scuff-x' WHERE item_name = '공용부 벽면 도장';
UPDATE quote_templates SET comment = '세라믹코트 or 수성도장' WHERE item_name = '발코니 도장';
UPDATE quote_templates SET comment = '카바링, 핸디, 망사, 실리콘, 사포, 포리퍼티 등' WHERE item_name = '부자재' AND work_type = '도장';
UPDATE quote_templates SET comment = '전체 샤시 래핑' WHERE item_name = '필름 래핑';
UPDATE quote_templates SET comment = '디아망 벽지' WHERE item_name = '전체 실크벽지';
UPDATE quote_templates SET comment = '실크벽지 부자재' WHERE item_name = '부자재' AND work_type = '도배';
UPDATE quote_templates SET comment = '수전 종류에 따라 비용변동' WHERE item_name = '세면수전';
UPDATE quote_templates SET comment = '수전 종류에 따라 비용변동' WHERE item_name = ' 매립세면수전';
UPDATE quote_templates SET comment = '수전 종류에 따라 비용변동' WHERE item_name = '샤워수전';
UPDATE quote_templates SET comment = '수전 종류에 따라 비용변동' WHERE item_name = ' 매립샤워수전';
UPDATE quote_templates SET comment = '수전 종류에 따라 비용변동' WHERE item_name = ' 슬라이드 바';
UPDATE quote_templates SET comment = '제작' WHERE item_name = '수납장';
UPDATE quote_templates SET comment = '수건걸이,휴지걸이' WHERE item_name = '욕실 악세서리';
UPDATE quote_templates SET comment = '아메리칸스탠다드기준 투피스' WHERE item_name = '변기';
UPDATE quote_templates SET comment = '아메리칸스탠다드기준' WHERE item_name = '세면대';
UPDATE quote_templates SET comment = '힘펠 휴젠뜨 2.5 버전 기준' WHERE item_name = '환풍기';
UPDATE quote_templates SET comment = '천장 smc자재 + 시공비' WHERE item_name = '욕실 천장';
UPDATE quote_templates SET comment = '도기 화물차배송' WHERE item_name = '배송비용';
UPDATE quote_templates SET comment = '3인치 COB 매입등' WHERE item_name = '3인치 매입등';
UPDATE quote_templates SET comment = 'T5 LED(900mm)' WHERE item_name = '간접등';
UPDATE quote_templates SET comment = '스위치 : 르그랑 또는 융\n콘센트 및 기타 : 르그랑 아펠라 기본형' WHERE item_name = '브랜드 스위치';
UPDATE quote_templates SET comment = '히든센서' WHERE item_name = '현관센서 인체감지기';
UPDATE quote_templates SET comment = '포인트 조명 세팅' WHERE item_name = '조명셋팅';
UPDATE quote_templates SET comment = '포인트 고급 콘센트 세팅 인건비' WHERE item_name = '콘센트셋팅';
UPDATE quote_templates SET comment = '지복득 원목마루(로스포함, 모델에 따라 변동)' WHERE item_name = '원목마루';
UPDATE quote_templates SET comment = '구정마루 광폭강마루\n(로스포함, 모델에 따라 변동)' WHERE item_name = '강마루';
UPDATE quote_templates SET comment = '구정마루 포레스타G\n(로스포함, 모델에 따라 변동)' WHERE item_name = '온돌마루';
UPDATE quote_templates SET comment = '수평몰탈 작업, 필요시 협의 후 진행' WHERE item_name = '셀프레벨링';
UPDATE quote_templates SET comment = 'PET지정컬러' WHERE item_name = '신발장';
UPDATE quote_templates SET comment = 'PET지정컬러' WHERE item_name = '현관 펜트리 수납장';
UPDATE quote_templates SET comment = 'PET지정컬러 / 블럼인티보서랍재 기본6개 적용' WHERE item_name = '주방가구';
UPDATE quote_templates SET comment = '그로헤 민타 크롬\n수전 종류에 따라 비용 변동있음.' WHERE item_name = '주방수전';
UPDATE quote_templates SET comment = '백조 깜뽀르테 960\n종류에 따라 비용 변동있음.' WHERE item_name = '씽크볼';
UPDATE quote_templates SET comment = '엘리카 제니스2 아일랜드 후드\n종류에 따라 비용 변동있음.' WHERE item_name = '후드';
UPDATE quote_templates SET comment = '밀레 후드일체형 인덕션\n(고객 구매)' WHERE item_name = '인덕션';
UPDATE quote_templates SET comment = '세라믹상판 1장당 자재비 + 시공비' WHERE item_name = '주방 상판';
UPDATE quote_templates SET comment = '11자 구성 30자 기준 견적금액\n제작 방식, 소재, 구성에 따라 비용변동' WHERE item_name = '드레스룸 제작가구';
UPDATE quote_templates SET comment = 'PET지정컬러 (실측 후 변동가능)' WHERE item_name = '붙박이장';
UPDATE quote_templates SET comment = 'PET지정컬러' WHERE item_name = '발코니 창고장';
UPDATE quote_templates SET comment = 'PET지정컬러 (실측 후 변동가능)' WHERE item_name = '거실 책장 제작';
UPDATE quote_templates SET comment = '3.5t 한대' WHERE item_name = '운임' AND work_type = '가구';
UPDATE quote_templates SET comment = '금속 하지 보강 재료비 + 인건비' WHERE item_name = '보강 및 기타';
UPDATE quote_templates SET comment = '사이즈에 따라 변동가능' WHERE item_name = '금속 선반';
UPDATE quote_templates SET comment = '삼성무풍 6대 냉방기 기준\n(브랜드, 모델에 따라 변동가능)' WHERE item_name = '시스템 에어컨';
UPDATE quote_templates SET comment = '별도 견적' WHERE item_name = '원격 제어 시스템';
UPDATE quote_templates SET comment = '별도 견적' WHERE item_name = '공기청정 시스템';
UPDATE quote_templates SET comment = '(커튼 및 홈스타일링 제품은 별도 견적 입니다.)\n(기본 베이스 조명은 포함이고, 포인트 벽등 또는 펜던트는 별도 금액입니다.)' WHERE item_name = '커튼 블라인드';
UPDATE quote_templates SET comment = '클로저, 말발굽, 보조키마개, 우유투입구마개' WHERE item_name = '현관방화문 부속교체';
